services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    hostname: gitlab.panov.local
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.panov.local:8088'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'lazypeon'
        prometheus['enable'] = true # Enable Prometheus monitoring
        prometheus['listen_address'] = '0.0.0.0:9090'
        nginx['listen_port'] = 80
        puma['worker_processes'] = 0 # disable Puma worker to avoid memory leak
  
    ports:
      - "8088:80"       # HTTP
      - "2424:22"       # SSH
      - "9090:9090"     # Prometheus
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - gitlab-network

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner/config:/etc/gitlab-runner
    environment:
      - CI_SERVER_URL=http://gitlab:8088
    networks:
      - gitlab-network
    extra_hosts:
      - "gitlab.panov.local:${GITLAB_IP}"  # Установите переменную GITLAB_IP=ваш_IP_ВМ

networks:
  gitlab-network:
    driver: bridge