version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.panov.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.panov.local'
        gitlab_rails['initial_root_password'] = 'lazypeon'
        gitlab_rails['initial_root_email'] = 'legkodogatca@gmail.com'
    ports:
      - "80:80"
      - "22:22"
      - "5000:5000" # flask for python
      - "8080:8080" # java for spring boot
      - "9090:9090" # for prometheus
    volumes:
      - ./srv/gitlab/config:/etc/gitlab
      - ./srv/gitlab/logs:/var/log/gitlab
      - ./srv/gitlab/data:/var/opt/gitlab