services:
  # GitLab CE (основной сервер)
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: "lazypeon"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.panov.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'lazypeon'
        prometheus['enable'] = true # Enable Prometheus monitoring
        prometheus['listen_address'] = '0.0.0.0:9090' # Listen on all interfaces
        nginx['listen_port'] = 80 # Use port 80 for GitLab web UI
        puma['worker_processes'] = 0 # disable Puma worker to avoid memory leak
      
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: r3g1str4t10n

    ports:
      # - "8088:80"       # GitLab Web UI
      - "2424:22"      # GitLab SSH
    volumes:
      - ./srv/gitlab/config:/etc/gitlab
      - ./srv/gitlab/logs:/var/log/gitlab
      - ./srv/gitlab/data:/var/opt/gitlab

  # GitLab Runner which auto registrating itself to GitLab
  # and become ready to run CI/CD pipelines for projects
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    entrypoint: [""]
    command: ["/bin/sh", "-c", "gitlab-runner register \
                                      --non-interactive \
                                      --url 'http://localhost:8088' \
                                      --registration-token 'r3g1str4t10n' \ 
                                      --executor 'docker' \
                                      --docker-network-mode 'host' \
                                      --docker-volumes '/var/run/docker.sock:/var/run/docker.sock' \
                                      --docker-image 'docker:latest' \
            && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
      - ./config:/etc/gitlab-runner
    network_mode: 'host'
    extra_hosts:
      - "gitlab.panov.local:host-gateway"
    depends_on:
      gitlab:
        condition: service_healthy
  
  # Creating local registry to deploy apps by GitLab CI/CD
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5001:5000"  # Outier 5001, inner 5000 (deafult Docker Registry port)
    restart: always
    volumes:
      - ./registry:/var/lib/registry  # Image storage(persistent)
  
  # CAdvisor for monitoring Docker containers
  # It collects metrics about running containers and provides a web UI.
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8081:8080" # Outier 8081, inner 8080 (deafult cAdvisor port)
    volumes:
      - /:/rootfs:ro # Root filesystem
      - /var/run:/var/run:ro # Docker runtime
      - /sys:/sys:ro # System files
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  # Prometheus for monitoring GitLab and other services
  # It collects metrics from GitLab and cAdvisor
  # and provides a web UI for viewing metrics.
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Outier 9090, inner 9090 (deafult Prometheus port)
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus configuration file
    restart: always