services:
  # GitLab CE (основной сервер)
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    environment:
      environment:
      GITLAB_ROOT_EMAIL: "legkodogatca@gmail.com"
      GITLAB_ROOT_PASSWORD: "lazypeon"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.panov.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'lazypeon'
        prometheus['enable'] = true # Enable Prometheus monitoring
        prometheus['listen_address'] = '0.0.0.0:9090'
        nginx['listen_port'] = 80
        puma['worker_processes'] = 0 # disable Puma worker to avoid memory leak
    ports:
      - "8088:80"       # GitLab Web UI
      - "2424:22"      # GitLab SSH
    volumes:
      - ./srv/gitlab/config:/etc/gitlab
      - ./srv/gitlab/logs:/var/log/gitlab
      - ./srv/gitlab/data:/var/opt/gitlab
    networks:
      - internal-net

  # GitLab Runner
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    networks:
      - internal-net

  # Flask приложение (порт 5000)
  flask-app:
    image: python:3.12-slim
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"    # Доступно на http://localhost:5000
    networks:
      - internal-net
    depends_on:
      - gitlab

  # Java приложение (порт 8080)
  java-app:
    image: java:17-slim
    build:
      context: ./java-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"    # Доступно на http://localhost:8080
    networks:
      - internal-net
    depends_on:
      - gitlab

networks:
  internal-net:
    driver: bridge
