services:
  # GitLab CE (основной сервер)
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.panov.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - "8088:80"       # GitLab Web UI
      - "2424:22"       # GitLab SSH
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - internal-net

  # GitLab Runner
  runner:
    image: gitlab/gitlab-runner:latest
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_config:/etc/gitlab-runner
    networks:
      - internal-net

  # Flask приложение (порт 5000)
  flask-app:
    image: python:3.12-slim
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"    # Доступно на http://localhost:5000
    networks:
      - internal-net
    depends_on:
      - gitlab

  # Java приложение (порт 8080)
  java-app:
    image: java:17-slim
    build:
      context: ./java-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"    # Доступно на http://localhost:8080
    networks:
      - internal-net
    depends_on:
      - gitlab

networks:
  internal-net:
    driver: bridge
