services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab-server
    restart: always
    environment:
      GITLAB_ROOT_EMAIL: "legkodogatca@gmail.com"
      GITLAB_ROOT_PASSWORD: "lazypeon"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8088'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'lazypeon'
        prometheus['enable'] = true # Enable Prometheus monitoring
        prometheus['listen_address'] = '0.0.0.0:9090'
        nginx['listen_port'] = 80
        puma['worker_processes'] = 0 # disable Puma worker to avoid memory leak
      
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: r3g1str4t10n
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - '8000:8000'
      - '2424:20'

    healthcheck:
      test: curl --fail http://localhost:8000/users/sign_in || exit 1
      interval: 60s
      timeout: 3s
      retries: 5

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    entrypoint: [""]
    command: ["/bin/sh", "-c", "gitlab-runner register \
                                      --non-interactive \
                                      --url 'http://localhost:8000' \
                                      --registration-token 'r3g1str4t10n' \ 
                                      --executor 'docker' \
                                      --docker-network-mode 'host' \
                                      --docker-image 'python:alpine' \
            && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
    network_mode: 'host'
    depends_on:
      gitlab:
        condition: service_healthy