services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    restart: always
    hostname: "${GITLAB_HOST}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        gitlab_rails['initial_root_email'] = '${GITLAB_ROOT_EMAIL}'
        gitlab_rails['initial_root_user'] = '${GITLAB_ROOT_USERNAME}'
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:2424"
      - "${GITLAB_FLASK_APP_PORT}:5000"
      - "${GITLAB_JAVA_APP_PORT}:8080"
      - "${GITLAB_PROMETHEUS_PORT}:9090"
    volumes:
      - ./srv/gitlab/config:/etc/gitlab
      - ./srv/gitlab/logs:/var/log/gitlab
      - ./srv/gitlab/data:/var/opt/gitlab